object BuildDependenciesVersions {
    const val APPCOMPAT = "1.5.1"
    const val MATERIAL = "1.8.0-alpha01"
    const val COROUTINES = "1.6.4"
    const val RECYCLE_VIEW = "1.2.1"
    const val NAVIGATION = "2.5.2"
    const val LIFECYCLE = "2.2.0"
    const val CORE_KTX = "1.5.0"
    const val FRAGMENT_KTX = "1.5.2"
    const val CONSTRAIN_LAYOUT = "2.1.4"
    const val SWIPE_REFRESH_LAYOUT = "1.2.0"
    const val PAGING = "3.1.1"
    const val TIMBER = "5.0.1"
    const val RETROFIT = "2.9.0"
    const val LOGGING = "4.10.0"
    const val MOSHI = "1.14.0"
    const val COIL = "2.2.1"
    const val LEAKCANARY = "2.9.1"
    const val DATABINDING = "3.5.0"
    const val PLAY_CORE = "1.10.3"
    const val KOIN = "3.2.0"

    // Tests
    const val TEST = "1.4.0"
    const val EXT = "1.1.2"
    const val ARCH_CORE = "2.1.0"
    const val JUNIT = "4.13.2"
    const val ROBOELECTRIC = "4.8.2"
    const val MOCKK = "1.12.7"
    const val ASSERTJ = "3.23.1"
    const val ESPRESSO = "3.5.0-alpha02"
    const val FRAGMENT_TEST = "1.2.5"
    const val MOCK_WEB_SERVER = "4.9.0"


}